# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sighting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Report URL')),
                ('classification', models.CharField(blank=True, default=b'A', max_length=1, null=True)),
                ('report_id', models.PositiveIntegerField(default=0, unique=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('year', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Year')),
                ('season', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Season')),
                ('month', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Month')),
                ('state', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'State')),
                ('county', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'County')),
                ('location_details', models.TextField(blank=True, null=True)),
                ('nearest_town', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'County')),
                ('nearest_road', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'County')),
                ('observed', models.TextField(blank=True, null=True)),
                ('also_noticed', models.TextField(blank=True, null=True)),
                ('other_witnesses', models.TextField(blank=True, null=True)),
                ('other_stories', models.TextField(blank=True, null=True)),
                ('time_and_conditions', models.TextField(blank=True, null=True)),
                ('environment', models.TextField(blank=True, null=True)),
                ('follow_up', models.TextField(blank=True, null=True)),
                ('about_investigator', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-date',),
                'verbose_name': 'Sighting',
                'verbose_name_plural': 'Sightings',
            },
        ),
    ]
