# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sighting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sighting',
            name='day',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Day'),
        ),
    ]
