# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sighting', '0002_sighting_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=25),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=25),
        ),
    ]
